### Test endpoint
POST http://localhost:3000/auth/test HTTP/1.1
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjQ5MTYyNjEyLCJleHAiOjE2NDkxNjI2Mjd9.sNMmAphCQ6cK_hOLVLz5yRt9Ul80sOPU67SGDj0SkqA



### Create new user
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "Pw12345_"
}

### Log In
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "Pw12345_"
}

### Refresh token
POST http://localhost:3000/auth/token HTTP/1.1
content-type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjQ5MTYyNTczfQ.IOO7ncXeuqBDvXk06f4P3Pz5Id7w_iltuFYDVaEoyJs"
}


### Log Out
POST http://localhost:3000/auth/signout HTTP/1.1
content-type: application/json

{
    "token": "Pw12345_"
}